# Generated by Django 4.0.5 on 2022-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(db_column='BIRTH', max_length=25),
        ),
    ]
