# Generated by Django 4.0.5 on 2022-11-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigame',
            name='game_type',
            field=models.CharField(choices=[(1, 'Corsi Block Test'), (2, 'Digit Span Test'), (3, 'K-TMT-E'), (4, 'K-BNT'), (5, 'SVLT-E')], db_column='MINI_GAME_TYPE', max_length=5),
        ),
    ]
