# Generated by Django 4.0.5 on 2022-11-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('device_type', models.CharField(choices=[(1, 'neurotx_v1'), (2, 'neurotx_v2')], db_column='DEVICE_TYPE', max_length=5)),
                ('sampling_rate', models.FloatField(db_column='SAMPLING_RATE')),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'NG_DEVICE',
            },
        ),
        migrations.CreateModel(
            name='BioSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('sample_size', models.IntegerField(db_column='SAMPLE_SIZE')),
                ('data', models.JSONField(db_column='DATA')),
                ('device', models.ForeignKey(db_column='DEVICE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_signal', to='signals.device')),
                ('game', models.ForeignKey(db_column='GAME_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_signal', to='game.game')),
            ],
            options={
                'db_table': 'NG_BIO_SIGNAL',
            },
        ),
    ]
