# Generated by Django 4.0.5 on 2022-11-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosignal',
            name='device_type',
            field=models.CharField(choices=[(1, 'neurotx_v1'), (2, 'neurotx_v2')], default='neurotx_v1', max_length=20),
        ),
    ]
