# Generated by Django 4.0.5 on 2022-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(1, 'neurotx_v1'), (2, 'neurotx_v2')], db_column='DEVICE_TYPE'),
        ),
    ]
