# Generated by Django 4.0.5 on 2022-11-16 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_minigame_game_type'),
        ('signals', '0002_alter_biosignal_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('device_type', models.CharField(choices=[(1, 'neurotx_v1'), (2, 'neurotx_v2')], db_column='DEVICE_TYPE', max_length=5)),
                ('sampling_rate', models.FloatField(db_column='SAMPLING_RATE')),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'NG_DEVICE',
            },
        ),
        migrations.RemoveField(
            model_name='biosignal',
            name='device_type',
        ),
        migrations.AddField(
            model_name='biosignal',
            name='data',
            field=models.JSONField(db_column='DATA', default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biosignal',
            name='game',
            field=models.ForeignKey(db_column='GAME_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_signal', to='game.game'),
        ),
        migrations.AddField(
            model_name='biosignal',
            name='device',
            field=models.ForeignKey(db_column='DEVICE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_signal', to='signals.device'),
        ),
    ]
