# Generated by Django 4.0.5 on 2022-11-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_device_remove_biosignal_device_type_biosignal_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosignal',
            name='sample_size',
            field=models.IntegerField(db_column='SAMPLE_SIZE', default=1),
            preserve_default=False,
        ),
    ]
